### ISSUE TITLE
ValueError: Parameter output_size must be > 0: 0.

### ISSUE THREAD

**Issue by yjyGo** [wesleytao/Dialogue-Generation-Imitation2RL#1]
Sorry to disturb, but I need help, I met this problem:
Traceback (most recent call last):
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/irl-gan.py", line 610, in <module>
    tf.app.run()
  File "/home/yangjy/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/irl-gan.py", line 605, in main
    gen_pre_train()
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/irl-gan.py", line 71, in gen_pre_train
    gens.train(gen_config)
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/generator.py", line 205, in train
    model = create_model(sess, gen_config, forward_only=False, name_scope=gen_config.name_model, word2id=vocab)
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/generator.py", line 61, in create_model
    model = seq2seq_model.Seq2SeqModel(gen_config, name_scope=name_scope, forward_only=forward_only)
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/gen_model.py", line 140, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/seq2seq.py", line 1093, in model_with_buckets
    decoder_inputs[:bucket[1]])
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/gen_model.py", line 138, in <lambda>
    lambda x, y: seq2seq_f(x, y, tf.where(self.forward_only, True, False)),
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/gen_model.py", line 107, in seq2seq_f
    mc_position=self.mc_position)
  File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/seq2seq.py", line 727, in embedding_attention_seq2seq
    cell = tf.contrib.rnn.OutputProjectionWrapper(cell, num_decoder_symbols)
  File "/home/yangjy/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell.py", line 358, in __init__
    raise ValueError("Parameter output_size must be > 0: %d." % output_size)
ValueError: Parameter output_size must be > 0: 0.

**Comment by KunyuNi** [comment]
> Sorry to disturb, but I need help, I met this problem: Traceback (most recent call last): File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/irl-gan.py", line 610, in tf.app.run() File "/home/yangjy/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run _sys.exit(main(argv)) File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/irl-gan.py", line 605, in main gen_pre_train() File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/irl-gan.py", line 71, in gen_pre_train gens.train(gen_config) File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/generator.py", line 205, in train model = create_model(sess, gen_config, forward_only=False, name_scope=gen_config.name_model, word2id=vocab) File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/generator.py", line 61, in create_model model = seq2seq_model.Seq2SeqModel(gen_config, name_scope=name_scope, forward_only=forward_only) File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/gen_model.py", line 140, in **init** softmax_loss_function=softmax_loss_function) File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/seq2seq.py", line 1093, in model_with_buckets decoder_inputs[:bucket[1]]) File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/gen_model.py", line 138, in lambda x, y: seq2seq_f(x, y, tf.where(self.forward_only, True, False)), File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/gen_model.py", line 107, in seq2seq_f mc_position=self.mc_position) File "/home/yangjy/PycharmProjects/Dialogue-Generation-Imitation2RL-master/gen/seq2seq.py", line 727, in embedding_attention_seq2seq cell = tf.contrib.rnn.OutputProjectionWrapper(cell, num_decoder_symbols) File "/home/yangjy/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell.py", line 358, in **init** raise ValueError("Parameter output_size must be > 0: %d." % output_size) ValueError: Parameter output_size must be > 0: 0.



> i am going to reproduce this paper , but i met  some problems  i need some help ,so i wanna your contanct information,
